// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcdAs891_oC3dx361Dpkn_69ECckbujeM',
    appId: '1:394946904824:web:e4241ef115dd498dc9f10d',
    messagingSenderId: '394946904824',
    projectId: 'the-exchange-online-98ddf',
    authDomain: 'the-exchange-online-98ddf.firebaseapp.com',
    storageBucket: 'the-exchange-online-98ddf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxvh91JxXNQh2JJo-yGn6JY_rEOcdYAgk',
    appId: '1:394946904824:android:6f80a99f2d821b59c9f10d',
    messagingSenderId: '394946904824',
    projectId: 'the-exchange-online-98ddf',
    storageBucket: 'the-exchange-online-98ddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFBpLNQS-xj4RJewQMf5R9ITTL7-kAjDI',
    appId: '1:394946904824:ios:8dc8fd97996b783fc9f10d',
    messagingSenderId: '394946904824',
    projectId: 'the-exchange-online-98ddf',
    storageBucket: 'the-exchange-online-98ddf.firebasestorage.app',
    iosBundleId: 'za.co.blackworks.theExchangeOnline',
  );
}
